/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces/$workspaceId'
import { Route as ClientVariationsRouteImport } from './routes/client/variations'
import { Route as ClientTeamRouteImport } from './routes/client/team'
import { Route as ClientSettingsRouteImport } from './routes/client/settings'
import { Route as ClientReportsRouteImport } from './routes/client/reports'
import { Route as ClientProjectsRouteImport } from './routes/client/projects'
import { Route as ClientOrganisationRouteImport } from './routes/client/organisation'
import { Route as ClientNotificationsRouteImport } from './routes/client/notifications'
import { Route as ClientMilestonesRouteImport } from './routes/client/milestones'
import { Route as ClientMessagesRouteImport } from './routes/client/messages'
import { Route as ClientLoginRouteImport } from './routes/client/login'
import { Route as ClientIssuesRouteImport } from './routes/client/issues'
import { Route as ClientInvoicesRouteImport } from './routes/client/invoices'
import { Route as ClientDocumentsRouteImport } from './routes/client/documents'
import { Route as ClientApprovalsRouteImport } from './routes/client/approvals'
import { Route as AdminVerificationRouteImport } from './routes/admin/verification'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AdminContractsRouteImport } from './routes/admin/contracts'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as ClientContractsIndexRouteImport } from './routes/client/contracts/index'
import { Route as AdminVerificationIndexRouteImport } from './routes/admin/verification/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSupportIndexRouteImport } from './routes/admin/support/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminContractsIndexRouteImport } from './routes/admin/contracts/index'
import { Route as AdminCompaniesIndexRouteImport } from './routes/admin/companies/index'
import { Route as ClientContractsWorkspaceIdRouteImport } from './routes/client/contracts/$workspaceId'
import { Route as AdminVerificationCompanyIdRouteImport } from './routes/admin/verification/$companyId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminSupportCaseIdRouteImport } from './routes/admin/support/$caseId'
import { Route as AdminSettingsRolesRouteImport } from './routes/admin/settings/roles'
import { Route as AdminContractsWorkspaceIdRouteImport } from './routes/admin/contracts/$workspaceId'
import { Route as AdminCompaniesCompanyIdRouteImport } from './routes/admin/companies/$companyId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)
const ClientVariationsRoute = ClientVariationsRouteImport.update({
  id: '/variations',
  path: '/variations',
  getParentRoute: () => ClientRoute,
} as any)
const ClientTeamRoute = ClientTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientReportsRoute = ClientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientRoute,
} as any)
const ClientOrganisationRoute = ClientOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMilestonesRoute = ClientMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ClientIssuesRoute = ClientIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ClientRoute,
} as any)
const ClientInvoicesRoute = ClientInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientRoute,
} as any)
const ClientApprovalsRoute = ClientApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ClientRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const ClientContractsIndexRoute = ClientContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminVerificationIndexRoute = AdminVerificationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVerificationRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminContractsIndexRoute = AdminContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContractsRoute,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCompaniesRoute,
} as any)
const ClientContractsWorkspaceIdRoute =
  ClientContractsWorkspaceIdRouteImport.update({
    id: '/contracts/$workspaceId',
    path: '/contracts/$workspaceId',
    getParentRoute: () => ClientRoute,
  } as any)
const AdminVerificationCompanyIdRoute =
  AdminVerificationCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AdminVerificationRoute,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminSupportCaseIdRoute = AdminSupportCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminSettingsRolesRoute = AdminSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminContractsWorkspaceIdRoute =
  AdminContractsWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => AdminContractsRoute,
  } as any)
const AdminCompaniesCompanyIdRoute = AdminCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AdminCompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/client': typeof ClientRouteWithChildren
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/contracts': typeof AdminContractsRouteWithChildren
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verification': typeof AdminVerificationRouteWithChildren
  '/client/approvals': typeof ClientApprovalsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/issues': typeof ClientIssuesRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/milestones': typeof ClientMilestonesRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/organisation': typeof ClientOrganisationRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/team': typeof ClientTeamRoute
  '/client/variations': typeof ClientVariationsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/admin/contracts/$workspaceId': typeof AdminContractsWorkspaceIdRoute
  '/admin/settings/roles': typeof AdminSettingsRolesRoute
  '/admin/support/$caseId': typeof AdminSupportCaseIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/verification/$companyId': typeof AdminVerificationCompanyIdRoute
  '/client/contracts/$workspaceId': typeof ClientContractsWorkspaceIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
  '/client/contracts/': typeof ClientContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/client/approvals': typeof ClientApprovalsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/issues': typeof ClientIssuesRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/milestones': typeof ClientMilestonesRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/organisation': typeof ClientOrganisationRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/team': typeof ClientTeamRoute
  '/client/variations': typeof ClientVariationsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/admin/contracts/$workspaceId': typeof AdminContractsWorkspaceIdRoute
  '/admin/settings/roles': typeof AdminSettingsRolesRoute
  '/admin/support/$caseId': typeof AdminSupportCaseIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/verification/$companyId': typeof AdminVerificationCompanyIdRoute
  '/client/contracts/$workspaceId': typeof ClientContractsWorkspaceIdRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
  '/admin/contracts': typeof AdminContractsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/verification': typeof AdminVerificationIndexRoute
  '/client/contracts': typeof ClientContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/client': typeof ClientRouteWithChildren
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/contracts': typeof AdminContractsRouteWithChildren
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verification': typeof AdminVerificationRouteWithChildren
  '/client/approvals': typeof ClientApprovalsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/issues': typeof ClientIssuesRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/milestones': typeof ClientMilestonesRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/organisation': typeof ClientOrganisationRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/team': typeof ClientTeamRoute
  '/client/variations': typeof ClientVariationsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/admin/contracts/$workspaceId': typeof AdminContractsWorkspaceIdRoute
  '/admin/settings/roles': typeof AdminSettingsRolesRoute
  '/admin/support/$caseId': typeof AdminSupportCaseIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/verification/$companyId': typeof AdminVerificationCompanyIdRoute
  '/client/contracts/$workspaceId': typeof ClientContractsWorkspaceIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
  '/client/contracts/': typeof ClientContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/client'
    | '/invitations'
    | '/login'
    | '/signup'
    | '/workspaces'
    | '/admin/audit-log'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/disputes'
    | '/admin/documents'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verification'
    | '/client/approvals'
    | '/client/documents'
    | '/client/invoices'
    | '/client/issues'
    | '/client/login'
    | '/client/messages'
    | '/client/milestones'
    | '/client/notifications'
    | '/client/organisation'
    | '/client/projects'
    | '/client/reports'
    | '/client/settings'
    | '/client/team'
    | '/client/variations'
    | '/workspaces/$workspaceId'
    | '/admin/'
    | '/client/'
    | '/workspaces/'
    | '/admin/companies/$companyId'
    | '/admin/contracts/$workspaceId'
    | '/admin/settings/roles'
    | '/admin/support/$caseId'
    | '/admin/users/$userId'
    | '/admin/verification/$companyId'
    | '/client/contracts/$workspaceId'
    | '/admin/companies/'
    | '/admin/contracts/'
    | '/admin/settings/'
    | '/admin/support/'
    | '/admin/users/'
    | '/admin/verification/'
    | '/client/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/invitations'
    | '/login'
    | '/signup'
    | '/admin/audit-log'
    | '/admin/disputes'
    | '/admin/documents'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/client/approvals'
    | '/client/documents'
    | '/client/invoices'
    | '/client/issues'
    | '/client/login'
    | '/client/messages'
    | '/client/milestones'
    | '/client/notifications'
    | '/client/organisation'
    | '/client/projects'
    | '/client/reports'
    | '/client/settings'
    | '/client/team'
    | '/client/variations'
    | '/workspaces/$workspaceId'
    | '/admin'
    | '/client'
    | '/workspaces'
    | '/admin/companies/$companyId'
    | '/admin/contracts/$workspaceId'
    | '/admin/settings/roles'
    | '/admin/support/$caseId'
    | '/admin/users/$userId'
    | '/admin/verification/$companyId'
    | '/client/contracts/$workspaceId'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verification'
    | '/client/contracts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/client'
    | '/invitations'
    | '/login'
    | '/signup'
    | '/workspaces'
    | '/admin/audit-log'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/disputes'
    | '/admin/documents'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verification'
    | '/client/approvals'
    | '/client/documents'
    | '/client/invoices'
    | '/client/issues'
    | '/client/login'
    | '/client/messages'
    | '/client/milestones'
    | '/client/notifications'
    | '/client/organisation'
    | '/client/projects'
    | '/client/reports'
    | '/client/settings'
    | '/client/team'
    | '/client/variations'
    | '/workspaces/$workspaceId'
    | '/admin/'
    | '/client/'
    | '/workspaces/'
    | '/admin/companies/$companyId'
    | '/admin/contracts/$workspaceId'
    | '/admin/settings/roles'
    | '/admin/support/$caseId'
    | '/admin/users/$userId'
    | '/admin/verification/$companyId'
    | '/client/contracts/$workspaceId'
    | '/admin/companies/'
    | '/admin/contracts/'
    | '/admin/settings/'
    | '/admin/support/'
    | '/admin/users/'
    | '/admin/verification/'
    | '/client/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  ClientRoute: typeof ClientRouteWithChildren
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/client/variations': {
      id: '/client/variations'
      path: '/variations'
      fullPath: '/client/variations'
      preLoaderRoute: typeof ClientVariationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/team': {
      id: '/client/team'
      path: '/team'
      fullPath: '/client/team'
      preLoaderRoute: typeof ClientTeamRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/reports': {
      id: '/client/reports'
      path: '/reports'
      fullPath: '/client/reports'
      preLoaderRoute: typeof ClientReportsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/projects': {
      id: '/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/organisation': {
      id: '/client/organisation'
      path: '/organisation'
      fullPath: '/client/organisation'
      preLoaderRoute: typeof ClientOrganisationRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/milestones': {
      id: '/client/milestones'
      path: '/milestones'
      fullPath: '/client/milestones'
      preLoaderRoute: typeof ClientMilestonesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/login': {
      id: '/client/login'
      path: '/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/issues': {
      id: '/client/issues'
      path: '/issues'
      fullPath: '/client/issues'
      preLoaderRoute: typeof ClientIssuesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/invoices': {
      id: '/client/invoices'
      path: '/invoices'
      fullPath: '/client/invoices'
      preLoaderRoute: typeof ClientInvoicesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/documents': {
      id: '/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/approvals': {
      id: '/client/approvals'
      path: '/approvals'
      fullPath: '/client/approvals'
      preLoaderRoute: typeof ClientApprovalsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/contracts/': {
      id: '/client/contracts/'
      path: '/contracts'
      fullPath: '/client/contracts/'
      preLoaderRoute: typeof ClientContractsIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/verification/': {
      id: '/admin/verification/'
      path: '/'
      fullPath: '/admin/verification/'
      preLoaderRoute: typeof AdminVerificationIndexRouteImport
      parentRoute: typeof AdminVerificationRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/contracts/': {
      id: '/admin/contracts/'
      path: '/'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AdminContractsIndexRouteImport
      parentRoute: typeof AdminContractsRoute
    }
    '/admin/companies/': {
      id: '/admin/companies/'
      path: '/'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
    '/client/contracts/$workspaceId': {
      id: '/client/contracts/$workspaceId'
      path: '/contracts/$workspaceId'
      fullPath: '/client/contracts/$workspaceId'
      preLoaderRoute: typeof ClientContractsWorkspaceIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/verification/$companyId': {
      id: '/admin/verification/$companyId'
      path: '/$companyId'
      fullPath: '/admin/verification/$companyId'
      preLoaderRoute: typeof AdminVerificationCompanyIdRouteImport
      parentRoute: typeof AdminVerificationRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/support/$caseId': {
      id: '/admin/support/$caseId'
      path: '/$caseId'
      fullPath: '/admin/support/$caseId'
      preLoaderRoute: typeof AdminSupportCaseIdRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/settings/roles': {
      id: '/admin/settings/roles'
      path: '/roles'
      fullPath: '/admin/settings/roles'
      preLoaderRoute: typeof AdminSettingsRolesRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/contracts/$workspaceId': {
      id: '/admin/contracts/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/admin/contracts/$workspaceId'
      preLoaderRoute: typeof AdminContractsWorkspaceIdRouteImport
      parentRoute: typeof AdminContractsRoute
    }
    '/admin/companies/$companyId': {
      id: '/admin/companies/$companyId'
      path: '/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AdminCompaniesCompanyIdRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
  }
}

interface AdminCompaniesRouteChildren {
  AdminCompaniesCompanyIdRoute: typeof AdminCompaniesCompanyIdRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
}

const AdminCompaniesRouteChildren: AdminCompaniesRouteChildren = {
  AdminCompaniesCompanyIdRoute: AdminCompaniesCompanyIdRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
}

const AdminCompaniesRouteWithChildren = AdminCompaniesRoute._addFileChildren(
  AdminCompaniesRouteChildren,
)

interface AdminContractsRouteChildren {
  AdminContractsWorkspaceIdRoute: typeof AdminContractsWorkspaceIdRoute
  AdminContractsIndexRoute: typeof AdminContractsIndexRoute
}

const AdminContractsRouteChildren: AdminContractsRouteChildren = {
  AdminContractsWorkspaceIdRoute: AdminContractsWorkspaceIdRoute,
  AdminContractsIndexRoute: AdminContractsIndexRoute,
}

const AdminContractsRouteWithChildren = AdminContractsRoute._addFileChildren(
  AdminContractsRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsRolesRoute: typeof AdminSettingsRolesRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsRolesRoute: AdminSettingsRolesRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminSupportRouteChildren {
  AdminSupportCaseIdRoute: typeof AdminSupportCaseIdRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
}

const AdminSupportRouteChildren: AdminSupportRouteChildren = {
  AdminSupportCaseIdRoute: AdminSupportCaseIdRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
}

const AdminSupportRouteWithChildren = AdminSupportRoute._addFileChildren(
  AdminSupportRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminVerificationRouteChildren {
  AdminVerificationCompanyIdRoute: typeof AdminVerificationCompanyIdRoute
  AdminVerificationIndexRoute: typeof AdminVerificationIndexRoute
}

const AdminVerificationRouteChildren: AdminVerificationRouteChildren = {
  AdminVerificationCompanyIdRoute: AdminVerificationCompanyIdRoute,
  AdminVerificationIndexRoute: AdminVerificationIndexRoute,
}

const AdminVerificationRouteWithChildren =
  AdminVerificationRoute._addFileChildren(AdminVerificationRouteChildren)

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCompaniesRoute: typeof AdminCompaniesRouteWithChildren
  AdminContractsRoute: typeof AdminContractsRouteWithChildren
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVerificationRoute: typeof AdminVerificationRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCompaniesRoute: AdminCompaniesRouteWithChildren,
  AdminContractsRoute: AdminContractsRouteWithChildren,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVerificationRoute: AdminVerificationRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientApprovalsRoute: typeof ClientApprovalsRoute
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientInvoicesRoute: typeof ClientInvoicesRoute
  ClientIssuesRoute: typeof ClientIssuesRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientMilestonesRoute: typeof ClientMilestonesRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientOrganisationRoute: typeof ClientOrganisationRoute
  ClientProjectsRoute: typeof ClientProjectsRoute
  ClientReportsRoute: typeof ClientReportsRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientTeamRoute: typeof ClientTeamRoute
  ClientVariationsRoute: typeof ClientVariationsRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientContractsWorkspaceIdRoute: typeof ClientContractsWorkspaceIdRoute
  ClientContractsIndexRoute: typeof ClientContractsIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientApprovalsRoute: ClientApprovalsRoute,
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientInvoicesRoute: ClientInvoicesRoute,
  ClientIssuesRoute: ClientIssuesRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientMilestonesRoute: ClientMilestonesRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientOrganisationRoute: ClientOrganisationRoute,
  ClientProjectsRoute: ClientProjectsRoute,
  ClientReportsRoute: ClientReportsRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientTeamRoute: ClientTeamRoute,
  ClientVariationsRoute: ClientVariationsRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientContractsWorkspaceIdRoute: ClientContractsWorkspaceIdRoute,
  ClientContractsIndexRoute: ClientContractsIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  ClientRoute: ClientRouteWithChildren,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
